name: Android CI

on:
  push:
    branches: [ master, dev ]
    name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Stable ID's map'
        required: true
        default: ''

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        env:
          ANDROID_BUILD_TOOLS_VERSION: ${{secrets.ANDROID_BUILD_TOOLS_VERSION}}
        run: |
          ./build.sh resources.xml $!
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: resources
          path: resources.arsc
