name: Android CI
on:
  push:
    branches: [ master]

  workflow_dispatch:
    inputs:
        resources:
            description: 'resources.xml'
            required: true
        ids:
            description: 'ids.txt'
            required: true

    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        env:
          ANDROID_BUILD_TOOLS_VERSION: ${{secrets.ANDROID_BUILD_TOOLS_VERSION}}
        run: |
          ./build.sh ${{ github.event.inputs.resources }}! ${{ github.event.inputs.ids }}!
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: resources
          path: resources.arsc
